# ndarray的创建

In [1]:
import numpy as np

## 基础的创建

In [ ]:
arr = np.array([1,2,3]) #独自创建
list = [4.4,5.4,6.4]
arr2 = np.array(list) #利用列表创建
arr3 = np.array(list,dtype=np.int64) #创建时修改数据类型
print(arr)
print(arr2)
print(arr3)

[1 2 3]
[4.4 5.4 6.4]
[4 5 6]


In [ ]:
arr_cp = np.copy(arr) #利用copy创建 只复制值，是一个新的ndarray
print(arr_cp)

[1 2 3]


In [ ]:
#固定创建
arr_0 = np.zeros((2,3))
arr_1 = np.ones((3,4))
arr_empty = np.empty((5,6))
arr_full = np.full((7,8),2026)
print(arr_0)
print(arr_1)
print(arr_empty)
print(arr_full)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[6.23042070e-307 7.56587584e-307 1.37961302e-306 6.23053614e-307
  1.69121639e-306 9.34595530e-307]
 [8.34424342e-308 1.24610383e-306 1.69118108e-306 8.06632139e-308
  1.20160711e-306 1.69119330e-306]
 [8.01095173e-307 2.22522597e-306 9.34611148e-307 1.60220393e-306
  1.42417221e-306 1.95820216e-306]
 [1.42417629e-306 1.95820216e-306 2.22523004e-306 1.37961981e-306
  1.37962456e-306 1.02360867e-306]
 [8.90111708e-307 6.89806849e-307 6.89811941e-307 1.11261162e-306
  1.11261434e-306 1.42410974e-306]]
[[2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026 2026 2026 2026]]


In [ ]:
#利用创建，但是只复制行列值，数值自己填
arr_like_0 = np.zeros_like(arr_full)
print(arr_like_0)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
